services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cinestars
      POSTGRES_PASSWORD: cinestars
      POSTGRES_DB: cinestars
    ports:
      - "5432:5432"
    volumes:
      - cinestars_db_data:/var/lib/postgresql/data

volumes:
  cinestars_db_data:
